# Generated by Django 4.1.7 on 2023-02-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cheese',
        ),
    ]
